from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import List, Optional, TypedDict


class VerificationResult(Enum):
    """Result from the verifier agent."""

    SUFFICIENT = "sufficient"
    INSUFFICIENT = "insufficient"


@dataclass
class DataDescription:
    """Description of a data file generated by the analyzer agent."""

    file_path: str
    description: str
    script: str


@dataclass
class ExecutionResult:
    """Result from executing a Python script."""

    success: bool
    output: str
    error: Optional[str] = None
    traceback: Optional[str] = None


class DSStarState(TypedDict, total=False):
    query: str
    data_files: List[str]
    data_descriptions: List[DataDescription]
    plan: List[str]
    code: str
    execution_results: List[str]
    last_execution: ExecutionResult
    iteration: int
    verification: VerificationResult
    verifier_response: str
    router_decision: str
    finalization_reason: str
    final_code: str
    final_plan: List[str]
    final_execution_results: List[str]

